### PR TITLE
commit icons file

### PR DESCRIPTION
**Pull request by jimmy5678998**

### CODE REVIEW

**Review by CurlyRhapsody — DISMISSED** [review]

**Comment by chanjeff2** [comment]
flutter_local_notification requires the use of drawable

**Comment by chanjeff2** [comment]
please also update name of app icon in fcm_handler

**Review by chanjeff2 — CHANGES_REQUESTED** [review]
need fix

**Comment by CurlyRhapsody** [comment]
Will be merging to another branch instead

**Pull request closed without merging**
